apiVersion: v1
kind: ServiceAccount
metadata:
  name: fitness-app-sa
  namespace: default
  annotations:
    # This Client ID tells Workload Identity which Azure Identity to assume
    # Replace the value below with the Client ID(managed identity)
    azure.workload.identity/client-id: "fce1e1d7-6f04-4078-b00f-7a709c3e4113"
  labels:
    azure.workload.identity/use: "true"
